### ISSUE TITLE
mythen3 dalist/dacvalues mismatch

### ISSUE THREAD

**Issue by anberga** [slsdetectorgroup/slsDetectorPackage#131]
dacvalues returns the wrong names for the dacs (shifted of 1)

$ sls_detector_get daclist
daclist [vcassh, vth2, vrshaper, vrshaper_n, vipre_out, vth3, vth1, vicin, vcas, vrpreamp, vcal_n, vipre, vishaper, vcal_p, vtrim, vdcsh, vthreshold]
$ sls_detector_get dacvalues
dacvalues [vth2 1200, vrshaper 2800, vrshaper_n 1280, vipre_out 2800, vth3 1220, vth1 2800, vicin 2800, vcas 1708, vrpreamp 1800, vcal_n 1100, vipre 1100, vishaper 2624, vcal_p 1708, vtrim 1712, vdcsh 2800, vthreshold 800, dac 0 2800]

**Comment by erikfrojdh** [comment]
This was due to a bug in the command line interface (CmdProxy.cpp line 965 and 969).  Pre C++17 the order of evaluation of the expressions were undefined. So in this case the iterator got incremented before the left most call to ToString. This issue is fixed from commit [9c58b48](https://github.com/slsdetectorgroup/slsDetectorPackage/commit/9c58b4802c40e344a5ca217d237b12b09f097a00)

A minimal example showing what not to do of the effect can be found on [https://godbolt.org/z/Ead7qz](https://godbolt.org/z/Ead7qz). Try switching between gcc 4.8 and gcc 7 (or newer). 

```cpp
std::vector<int> vec{0,1,2,3};
auto it = vec.cbegin();
std::cout << "vec: " << *it << " " << *it++ << " " << *it++ <<'\n'; \\This order of evaluation is undefined pre C++17

```

More reading

[http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-order-fct](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-order-fct )
