### ISSUE TITLE
Wrong progress in acquire

### ISSUE THREAD

**Issue by anberga** [slsdetectorgroup/slsDetectorPackage#134]
##### *Distribution: 

RHEL7

##### *Detector type: 

Mythen3
##### *Software Package Version: 

developer
##### Priority:

Low
##### *Describe the bug

Client:
sls_detector_put frames 1000
sls_detector_acquire 
 95.00 %
Acquired [500]

On the receiver:
- 09:34:56.082 INFO: Summary of Port 60005
        Missing Packets         : 1000
        Complete Frames         : 500
        Last Frame Caught       : 26391

received 50% of the frames and of the packets (running at high frame rates) but the progress is 95%

##### Expected behavior

I expected 
sls_detector_acquire 
 **50.00 %**
Acquired [500]

**Comment by thattil** [comment]
Here, the progress is 95% and should not be 50%. This is from the frame number caught to know what the progress of the acquisition is  and not based on how many complete frames were caught.

In fact, "Acquired[500]" means it got 500 frames, instead of 1000. 

Therefore, 
sls_detector_acquire
95.00 %
Acquired [500]
This shows you both the last polled status of the acquisition and how many complete frames it got. (which is also consistent with the receiver)
