### ISSUE TITLE
Corruption of h5 files: Zeros and (2¹⁶-1) appended after "real" frames

### ISSUE THREAD

**Issue by vhinger182** [slsdetectorgroup/slsDetectorPackage#474]
##### *Describe the bug

Was observed when using Jungfrau in storage cell mode and switching between 16 storage cells and normal operation (with single storage cell no. 15). h5 data files produced in normal mode sometimes contain "crap" data appended after real frame data. E.g. if we set 200 frames, these 200 frames are correct and afterwards follow frames with value (2¹⁶-1) for data and zeros for storage cell number. It seems the receiver is preparing the length of the h5 files wrongly and filling the missing frames with defaults.

##### Distribution: 

not applicable

##### Detector type or Receiver: 

Receiver used with Jungfrau

##### Software Package Version: 

6.1.1

##### Priority:

Medium

##### Expected behavior

Only real frames should be written to file.

##### To Reproduce

Not 100% clear atm. Needs to be investigated systematically. Probably some sequence like this: Operate Jungfrau in storage cell mode with all 15 storage cells + receiver running. Take e.g. 20-100 frames (100 frames with 16 storage cells means 1600 frames are written to file). Switch to normal mode (only storage cell 15) + keep receiver running. Take normal mode data. Here, we expect "crap" to be appended to the file.

**Comment by thattil** [comment]
Yes, it makes sense. Currently, the hdf5 files created are for a fixed size determined by "#frames * #triggers * #storage cell -1".
The receiver expects the number of frames it calculates at "rx_start" and normally this does not change during an acquisition.
Each time you do 'p start', it should extend the dataset by "numImages".

Additional bug:
There was a bug in the code that actually "did not" update the receiver of a number of storage cell change. If this had been done correctly, it would not have allowed you to update this value in the receiver (exception thrown because receiver is not idle).

Suggested solution:
- Update receiver when changing "extrastoragecells".
- Allow receiver to be updated even when not idle.
- update numImages in "extenddataset".

FYI:
p rx_start... p start. p start... p rx_stop Is not the normal way of things. The summary and the number of images (expected) in the master file will be incorrect. In the developer branch, however, it will also state the "Frames in File" caught by the first receiver in the master file.

Stop Issue:
This solution will not solve your issue if you do a "p stop". Then the frames received are less than the dataset size created for an acquisition. A solution for this, I will figure out when I am back with a lower priority as you still have the "Frame in File" feature to figure out how many to read. I will create an issue for this.
