### ISSUE TITLE
[Mythen III] Stop pulse assigned to wrong address

### ISSUE THREAD

**Issue by kozlowp1** [slsdetectorgroup/slsDetectorPackage#631]
In MIII when using command "p stop" a wrong bit is toggled. The stop bit is on the address 0x84, second bit.

This works: "p reg 0x84 0x2"

**Comment by thattil** [comment]
It is connected to the same bit and the same register in the software register map.

**Comment by thattil** [comment]
This is due to the fact that the stop command will not reach the detector if it is already in idle or stopped state. Added in 6.1.2 to handle simultaneous asynchronous start and stop commands from multiple processes to multiple detectors. https://github.com/slsdetectorgroup/slsDetectorPackage/pull/585
