### ISSUE TITLE
Eiger: Blocking trigger on quad

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/slsDetectorPackage#762]
Blocking software trigger not blocking on quad. 7.0.1

**Comment by thattil** [comment]
Seems to be the issue with a single half module as well (quad or not). The signal ready to trigger is up before the acquisition is done. @mbrueckner-psi is having a look at the firmware or creating a new one currently.

**Comment by mbrueckner-psi** [comment]
Explanation:
Feb_Control_IsReadyForTrigger() uses bit 5 of FEB r/o reg 3 which is "chips_ready_for_trigger_in" in the FPGA design. This "chip_ready_for_trigger_in" signal is before it is combined with the internal signals from it's own state machine (and the one from the left FEB). This is fine for all slaves and therefore for all multi-module detectors. On a single halfmodule detector the incoming signal is always '1' since no slave pulls it down.

Fix:
My fix is to provide "chips_ready_for_signal" from after the combination with its own state machine signals. To make it is easier for me, I attach this signal to r/o reg 0 bit 26 (counting from 0).
This new firmware will carry version 32.

**Comment by mbrueckner-psi** [comment]
Thinking of it, I'll change the original bit 5 of FEB r/o reg 3 such that no software change in needed.

**Comment by mbrueckner-psi** [comment]
The firmware is available now in AFS /afs/psi.ch/project/pilatusXFS/Firmware/bitfiles/v32/
Please test it

**Comment by thattil** [comment]
Requiring fw version 32 from 7.0.3 onwards (therefore also 8.0.0)
