### ISSUE TITLE
Stop master and slave modules of 25 um G2 with the same frame number

### ISSUE THREAD

**Issue by jiaguozhang** [slsdetectorgroup/slsDetectorPackage#945]
For 25 um G2 module, when stopping the data acquisition during taking data, slave may receive one more trigger and take 2720 images more than the master module. Both should finish at the same amount of image. Need to implement a constraint either in the software (receiver) or firmware to have a pre-stop at a given frame number? To be discussed for release 9.

##### *Detector type: 

Gotthard2

##### *Software Package Version: 

< 8.0.2

##### Priority:

Medium

##### *State the feature:

Stop the master and slave to make them having the same number of frames sent out.

**Comment by thattil** [comment]
Since setting the next frame number is connected, whenever we do a 'stop', one can get the next frame number, get a max from all the modules, +1 and set this value to all modules. This is anyway done in the client. Have to connect the command to its registers in G2. Registers 0xC and 0xD like module id register.

**Comment by thattil** [comment]
Awaiting @lopez-c info on if get next frame number registers exist. If not, then a variable that starts up as 1 at server start up. and calculates the next frame number using frames left .
